export function dashboardHtml(): string {
  return `<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>CommandCode Bridge Console</title>
  <style>
    :root {
      --paper:#d8d0bc; --paper-2:#c9bfaa; --ink:#302d27; --muted:#6f6658;
      --line:#8e846f; --panel:#bdb39f; --panel-2:#aca18c; --accent:#7c6f55;
      --good:#3e6546; --warn:#8a6635; --bad:#7a4141; --disabled:#8d8779;
      --mono: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
      --sans: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }
    *{box-sizing:border-box} body{margin:0;background:linear-gradient(180deg,var(--paper),#cfc6b2);color:var(--ink);font-family:var(--sans);font-size:14px;}
    body::before{content:"";position:fixed;inset:0;pointer-events:none;background-image:linear-gradient(rgba(62,58,50,.12) 1px,transparent 1px),linear-gradient(90deg,rgba(62,58,50,.12) 1px,transparent 1px);background-size:18px 18px;mix-blend-mode:multiply;}
    .wrap{width:min(100%,1040px);margin:0 auto;padding:12px 10px 80px}.top{display:flex;gap:10px;align-items:flex-start;justify-content:space-between;margin-bottom:10px}.brand{border-top:2px solid var(--ink);padding-top:8px}.eyebrow{font:700 11px/1 var(--mono);letter-spacing:.14em;color:var(--muted);text-transform:uppercase}.brand h1{font-size:22px;line-height:1.05;margin:4px 0 2px;letter-spacing:-.03em}.status{min-width:118px;text-align:right;font-family:var(--mono);font-size:11px}.pill{display:inline-flex;align-items:center;gap:6px;border:1px solid var(--line);background:rgba(255,255,255,.18);padding:5px 7px}.dot{width:8px;height:8px;border-radius:99px;background:var(--disabled)}.dot.on{background:var(--good)}.dot.off{background:var(--bad)}
    .grid{display:grid;grid-template-columns:1fr;gap:10px}.card{background:rgba(189,179,159,.88);border:1px solid var(--line);box-shadow:inset 0 1px rgba(255,255,255,.25);padding:10px}.card h2{display:flex;align-items:center;justify-content:space-between;font-size:13px;letter-spacing:.04em;text-transform:uppercase;margin:0 0 8px;border-bottom:1px solid var(--line);padding-bottom:6px}.sub{color:var(--muted);font-size:12px}.row{display:flex;gap:8px;align-items:center;justify-content:space-between;margin:6px 0}.stack{display:grid;gap:7px}.field{display:grid;gap:4px}.field label{font:700 10px/1 var(--mono);letter-spacing:.08em;color:var(--muted);text-transform:uppercase}input,select,button{font:inherit}input,select{width:100%;min-height:38px;border:1px solid var(--line);background:#d9d0bd;color:var(--ink);padding:8px}button{min-height:40px;border:1px solid var(--ink);background:var(--ink);color:var(--paper);padding:8px 10px;text-transform:uppercase;letter-spacing:.06em;font-size:11px;font-weight:700}button.secondary{background:transparent;color:var(--ink);border-color:var(--line)}button.danger{background:var(--bad);border-color:var(--bad)}button:disabled{background:var(--disabled);border-color:var(--disabled);opacity:.55}.seg{display:grid;grid-template-columns:1fr 1fr;gap:6px}.policy{border:1px solid var(--line);padding:8px;background:rgba(216,208,188,.45)}.policy input{width:auto;min-height:0}.policy b{display:block;font-size:12px}.policy span{display:block;color:var(--muted);font-size:11px;margin-top:2px}.kv{display:grid;grid-template-columns:1fr auto;gap:4px;font-family:var(--mono);font-size:11px;border-bottom:1px dashed rgba(80,72,60,.35);padding:4px 0}.model,.cred{border:1px solid var(--line);background:rgba(216,208,188,.4);padding:8px;display:grid;gap:7px}.model-head,.cred-head{display:flex;gap:8px;align-items:center;justify-content:space-between}.switch{position:relative;width:48px;height:26px;flex:0 0 auto}.switch input{display:none}.slider{position:absolute;inset:0;border:1px solid var(--line);background:var(--disabled)}.slider:before{content:"";position:absolute;width:18px;height:18px;left:3px;top:3px;background:var(--paper);transition:.18s} .switch input:checked+.slider{background:var(--good)}.switch input:checked+.slider:before{transform:translateX(22px)}.small{font-size:11px;color:var(--muted)}.token{font-family:var(--mono);font-size:11px}.footerbar{position:fixed;left:0;right:0;bottom:0;background:rgba(48,45,39,.94);color:var(--paper);padding:8px 10px;display:flex;gap:8px;align-items:center;justify-content:center}.footerbar button{background:var(--paper);color:var(--ink)}.footerbar button.restart.active{background:#d7b56d}.toast{position:fixed;left:10px;right:10px;bottom:62px;background:var(--ink);color:var(--paper);padding:10px;border:1px solid var(--line);display:none}.toast.show{display:block}
    @media(min-width:760px){.wrap{padding:22px 18px 90px}.grid{grid-template-columns:1.1fr .9fr}.wide{grid-column:1/-1}.brand h1{font-size:30px}.seg{grid-template-columns:repeat(4,1fr)}.models{grid-template-columns:repeat(3,1fr);display:grid}.creds{grid-template-columns:repeat(2,1fr);display:grid}.top{align-items:center}}
  </style>
</head>
<body>
  <main class="wrap">
    <section class="top">
      <div class="brand"><div class="eyebrow">YoRHa / Local OpenAI-Compatible Provider</div><h1>CommandCode Bridge Console</h1><div class="sub">mobile-first operations panel · NieR HELP tone</div></div>
      <div class="status"><span class="pill"><i id="dot" class="dot"></i><span id="online">checking</span></span><div id="endpoint" class="small"></div></div>
    </section>
    <section class="grid">
      <div class="card"><h2>Access Key <span class="sub">local only</span></h2><div class="field"><label>Bridge API Key</label><input id="bridgeKey" type="password" placeholder="BRIDGE_API_KEY" /></div><div class="row"><button id="saveKey" class="secondary">Save key</button><button id="refresh">Refresh</button></div></div>
      <div class="card"><h2>Bridge State</h2><div id="state"></div></div>
      <div class="card wide"><h2>Server Bind <span class="sub">after restart</span></h2><div class="grid"><div class="field"><label>Bind host</label><select id="bindHost"><option value="127.0.0.1">127.0.0.1 · local only</option><option value="0.0.0.0">0.0.0.0 · LAN/Tailscale</option></select></div><div class="field"><label>Port</label><input id="bindPort" type="number" min="1" max="65535" /></div></div><p class="small">0.0.0.0은 Tailscale/LAN에서 접근 가능합니다. 외부 노출 시 BRIDGE_API_KEY를 유지하세요.</p></div>
      <div class="card wide"><h2>Routing Policy <span class="sub">default: daily burn</span></h2><div id="policies" class="seg"></div><div class="grid" style="margin-top:8px"><div class="field"><label>Max in-flight / key</label><input id="maxPer" type="number" min="1" /></div><div class="field"><label>Total max = key ×</label><input id="maxMult" type="number" min="1" /></div></div><p class="small">DeepSeek V4 Flash 부하테스트에서 8-way 병렬은 안정적이었고, 운영 기본값은 안전하게 key당 4를 권장합니다.</p></div>
      <div class="card wide"><h2>Credentials <button id="addCred" class="secondary">Add key</button></h2><div id="creds" class="stack creds"></div></div>
      <div class="card wide"><h2>Models <span class="sub">on/off after restart</span></h2><div id="models" class="stack models"></div></div>
    </section>
  </main>
  <div class="footerbar"><span id="dirtyText" class="token">no pending changes</span><button id="save" class="secondary">Save JSON</button><button id="restart" class="restart" disabled>Restart Bridge</button></div>
  <div id="toast" class="toast"></div>
<script>
const policies=[['daily_burn_priority','잔액/남은일수 우선','만료 전 써야 할 크레딧을 먼저 태움'],['balance_priority','잔액 많은 순','현재 잔액이 큰 key 우선'],['round_robin','순환 분산','요청마다 key를 순서대로 선택'],['drain_first','앞 key 소진','1번 key부터 다 쓰고 다음 key로 이동']];
let cfg=null, dirty=false;
const $=id=>document.getElementById(id); const toast=t=>{ $('toast').textContent=t; $('toast').classList.add('show'); setTimeout(()=>$('toast').classList.remove('show'),2500); };
function auth(){return {'authorization':'Bearer '+localStorage.getItem('bridgeApiKey'),'content-type':'application/json'}}
function setDirty(v=true){dirty=v; $('dirtyText').textContent=v?'pending changes · restart required':'no pending changes'; updateRestart();}
function updateRestart(){const online=$('online').textContent==='online'; $('restart').disabled=online&&!dirty; $('restart').classList.toggle('active',!$('restart').disabled)}
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{...auth(),...(opt.headers||{})}}); if(!r.ok) throw new Error(await r.text()); return r.json();}
async function load(){try{const h=await fetch('/health').then(r=>r.json()); $('dot').className='dot on'; $('online').textContent='online'; $('endpoint').textContent=(h.endpoint||((location.hostname||'127.0.0.1')+':'+location.port));}catch{ $('dot').className='dot off'; $('online').textContent='offline'; } updateRestart(); try{cfg=await api('/admin/config'); try{const m=await api('/admin/commandcode/credentials?refresh=true'); const byId=new Map((m.credentials||[]).map(x=>[x.id,x])); cfg.credentials.forEach(c=>c.metrics=byId.get(c.id));}catch{} render(); setDirty(cfg.dirty||false);}catch(e){toast('API key required or invalid');}}
function render(){if(!cfg)return; $('state').innerHTML=[['Bind',cfg.server.host+':'+cfg.server.port],['Policy',cfg.routing.policy],['Credentials',cfg.credentials.length],['Max/key',cfg.routing.maxInFlightPerCredential],['Max total','key × '+cfg.routing.maxTotalInFlightMultiplier],['Config',cfg.configFilePath||'env only']].map(([k,v])=>'<div class="kv"><span>'+k+'</span><b>'+v+'</b></div>').join(''); $('bindHost').value=cfg.server.host; $('bindPort').value=cfg.server.port; $('maxPer').value=cfg.routing.maxInFlightPerCredential; $('maxMult').value=cfg.routing.maxTotalInFlightMultiplier;
$('policies').innerHTML=policies.map(p=>'<label class="policy"><input type="radio" name="policy" value="'+p[0]+'" '+(cfg.routing.policy===p[0]?'checked':'')+'><b>'+p[1]+'</b><span>'+p[2]+'</span><span class="token">'+p[0]+'</span></label>').join(''); document.querySelectorAll('input[name=policy]').forEach(el=>el.onchange=()=>{cfg.routing.policy=el.value;setDirty();});
$('creds').innerHTML=cfg.credentials.map((c,i)=>{c.originalId=c.originalId||c.id; const m=c.metrics||{}; const b=m.billing||{}; const remaining=(b.remainingCredits??b.currentBalance??b.monthlyCredits??'unknown'); const until=b.currentPeriodEnd||b.periodEnd||'unknown'; const burn=b.requiredDailyBurn??b.dailyBurnRequired??'unknown'; return '<div class="cred"><div class="cred-head"><b>'+(c.id||('key'+(i+1)))+'</b><button class="danger" data-del="'+i+'">Delete</button></div><div class="kv"><span>Status</span><b>'+(m.available===false?'blocked':'ready')+'</b></div><div class="kv"><span>Credits / Days</span><b>'+remaining+' / '+until+'</b></div><div class="kv"><span>Burn need</span><b>'+burn+'</b></div><div class="field"><label>Name</label><input data-cid="'+i+'" value="'+(c.id||'')+'"></div><div class="field"><label>API Key '+(c.apiKeyConfigured?'('+c.apiKeyPreview+')':'')+'</label><input data-ckey="'+i+'" type="password" placeholder="leave blank to keep existing"></div><div class="field"><label>Max in-flight override</label><input data-cmax="'+i+'" type="number" min="1" value="'+(c.maxInFlight||'')+'"></div></div>'}).join('');
document.querySelectorAll('[data-cid]').forEach(e=>e.oninput=()=>{cfg.credentials[+e.dataset.cid].id=e.value;setDirty();}); document.querySelectorAll('[data-ckey]').forEach(e=>e.oninput=()=>{cfg.credentials[+e.dataset.ckey].apiKey=e.value;setDirty();}); document.querySelectorAll('[data-cmax]').forEach(e=>e.oninput=()=>{cfg.credentials[+e.dataset.cmax].maxInFlight=Number(e.value)||undefined;setDirty();}); document.querySelectorAll('[data-del]').forEach(e=>e.onclick=()=>{cfg.credentials.splice(+e.dataset.del,1);render();setDirty();});
$('models').innerHTML=cfg.models.map((m,i)=>'<div class="model"><div class="model-head"><div><b>'+ (m.label||m.id) +'</b><div class="small">'+m.provider+' · '+m.id+'</div></div><label class="switch"><input data-mid="'+i+'" type="checkbox" '+(m.enabled?'checked':'')+'><span class="slider"></span></label></div><div class="small">'+(m.notes||'')+'</div></div>').join(''); document.querySelectorAll('[data-mid]').forEach(e=>e.onchange=()=>{cfg.models[+e.dataset.mid].enabled=e.checked;setDirty();});}
$('saveKey').onclick=()=>{localStorage.setItem('bridgeApiKey',$('bridgeKey').value);load();}; $('refresh').onclick=load; $('bindHost').onchange=()=>{cfg.server.host=$('bindHost').value;setDirty();}; $('bindPort').oninput=()=>{cfg.server.port=Number($('bindPort').value)||9992;setDirty();}; $('maxPer').oninput=()=>{cfg.routing.maxInFlightPerCredential=Number($('maxPer').value)||4;setDirty();}; $('maxMult').oninput=()=>{cfg.routing.maxTotalInFlightMultiplier=Number($('maxMult').value)||3;setDirty();}; $('addCred').onclick=()=>{cfg.credentials.push({id:'key'+(cfg.credentials.length+1),apiKey:'',weight:1});render();setDirty();};
$('save').onclick=async()=>{const payload={server:cfg.server,routing:cfg.routing,models:cfg.models,credentials:cfg.credentials.map(c=>({id:c.id,originalId:c.originalId,apiKey:c.apiKey||undefined,weight:c.weight||1,maxInFlight:c.maxInFlight,allowedModels:c.allowedModels}))}; cfg=await api('/admin/config',{method:'PUT',body:JSON.stringify(payload)}); render(); setDirty(true); toast('JSON saved. Restart required.');};
$('restart').onclick=async()=>{await api('/admin/restart',{method:'POST',body:'{}'}); toast('Restart requested'); setTimeout(load,1800);};
$('bridgeKey').value=localStorage.getItem('bridgeApiKey')||''; load();
</script>
</body></html>`;
}
